# Generated by Django 5.1.3 on 2024-12-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_likehistory_user_alter_listeninghistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likehistory',
            name='liked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='listened_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
